### ISSUE TITLE
Mnesia is Overloaded at about 60Sms/Second

### ISSUE THREAD

**Issue by dergraf** [K2InformaticsGmbH/imem#1]
I got the following Error Reports on one of the nodes (probably the one that got more sessions through the balancer) at about 60 Sms/Second. Every successful Sms-Forwarding should put 4 new Log records into the database (therefore about 240 dirty writes per second).

=ERROR REPORT==== 14-Jan-2013::16:26:03 ===
Mnesia('stag@mstk2mpx1.it.bwns.ch'): *\* WARNING *\* Mnesia is overloaded: {dump_log,
                                                                          write_threshold}

=ERROR REPORT==== 14-Jan-2013::16:26:03 ===
*\* Generic server imem_if terminating
*\* Last message in was {mnesia_system_event,
                           {mnesia_overload,{dump_log,write_threshold}}}
*\* When Server state == ok
*\* Reason for termination ==
*\* {badarith,[{imem_if,handle_info,2,[{file,"src/imem_if.erl"},{line,592}]},
              {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,227}]}]}
imem_if no node found at 'stag@mstk2mpx1.it.bwns.ch' for schema 'Imem' in erlang cluster mpro
imem_if started as disc!

=ERROR REPORT==== 14-Jan-2013::16:27:28 ===
Mnesia('stag@mstk2mpx1.it.bwns.ch'): *\* WARNING *\* Mnesia is overloaded: {dump_log,
                                                                          write_threshold}

=ERROR REPORT==== 14-Jan-2013::16:27:28 ===
*\* Generic server imem_if terminating
*\* Last message in was {mnesia_system_event,
                           {mnesia_overload,{dump_log,write_threshold}}}
*\* When Server state == ok
*\* Reason for termination ==
*\* {badarith,[{imem_if,handle_info,2,[{file,"src/imem_if.erl"},{line,592}]},
              {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,227}]}]}
SchemaDir "/home/mpro/projects/git/mpro/Imem.stag@mstk2mpx1.it.bwns.ch"
imem_if sleeping for 888 ms...
imem_if no node found at 'stag@mstk2mpx1.it.bwns.ch' for schema 'Imem' in erlang cluster mpro
imem_if started as disc!

**Comment by c-bik** [comment]
Not reproduced.
