### ISSUE TITLE
Automatic snapshotting of Dyn tables should be supressed

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/imem#117]
Seen on CPRO Staging  
    {
        "logTime": "19.01.2017 11:29:45.148963",
        "logLevel": "info",
        "pid": "<0.2269.0>",
        "module": "imem_snap",
        "function": "handle_info",
        "line": 0,
        "node": "'cpro@ZHHAPMOP-SBSM01.it.bwns.ch'",
        "fields": "[snapshot]",
        "message": "snapshot created for cproNodeJobDyn@ZHHAPMOPSBSM01",
        "stacktrace": "[]"
    }

**Comment by shamis** [comment]
will be fixed by #123

**Comment by c-bik** [comment]
@shamis this issue requires calling `imem_snap:exclude_table_pattern` form CPro.

**Comment by shamis** [comment]
Implementation used in the required application
