### ISSUE TITLE
imem:now() implementation of monotonic, adapted, unique timestamp

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/imem#146]
to be implemented in branch `imem_now`

List of questions to be discussed and checked:

imem module implements now() in new format (4-tuple instead of 3-tuple)

imem.set_start_time(Node) 
Changed from erlang:now to erlang:timestamp (keeping the 3-tuple format).
Where do we need this start_time env variable?
Is it reasonable to measure in the scope of the first starting node (TimeKeeper)?
What happens, when the TimeKeeper is dead?

imem:join_erl_cluster
Whar happens, if this is a cold start?
Will start_time be added to the application:env ?

**Comment by stoch** [comment]
@c-bik 

what is the exact type of time in imem_dal_skvh_load ?

`-record(loadOutput,
                  { operation = channel     ::atom()
                  , keycounter = 0          ::integer()
                  , keys = []               ::list()
                  , time                    ::any() 
                  , totalread = 0           ::integer()
                  , rate = 0                ::float()                  
                  , lastItem                ::any()
                  , lastValue               ::any()
                  }
        ).`

Options will be (see imem_if.hrl):

`-type ddTimeUID() :: 'undefined' | {integer(), integer(), atom(), integer()}.   % {Secs,Micro,Node,UniqueInteger}`

`-type ddTimestamp() :: 'undefined' | {integer(), integer(), integer()}.         % {Mega,Secs,Micro}
`

**Comment by acautin** [comment]
@c-bik any update on this ?

**Comment by shamis** [comment]
fixed in #151
