### ISSUE TITLE
ReceiveData does not terminate

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/imem#157]
It seems, that ReceiveData does not properly terminate. 
Seen in egambo with a big sender query (more than 23'000 rows) from which I wanted 10'000. I typed 10000 into the yellow field on the sender and awaited the fetch.
Then I clicked 'SendData'. On the receiver, i clicked 'ReceiveData' which fetched 10'000 rows and then remained active for minutes. The spinner was turning and after several minutes, fetching to the end on the sender side resulted in all rows received on the receiver side.
Expected behaviour: After a timeout (maybe 1 minute by default) the data sender and the data receiver processes must terminate.
To be checked: Closing the sender statement must either immediately terminates the receiver or it must terminate after the timeout (1 minute), because of data starvation.

**Comment by shamis** [comment]
Process can be terminated by closing either of the receiver or sender table in dderl. This will stop both sender and receiver process. Sender have to be started first when sending data and if the receiver is not started with in 100 seconds (default value - configurable `[{dderl,dderl_data_sender,connectTimeout}]`) the sender will terminate. If the sender is not active and if we try to receive data, we get a message `No table sending data`. Closing the progress dialog box will not stop sending and receiving processes.
