### ISSUE TITLE
insert to ddTrace crash

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/imem#198]
Branch https://github.com/K2InformaticsGmbH/imem/tree/dbg_tracer

![image](https://user-images.githubusercontent.com/913008/38106143-6d63b19a-338e-11e8-81c9-eb15b2a20395.png)

```erlang
[error] [_DDRL_] {dderl_fsm,383} update_cursor_prepare(
[[1,ins,{{},{}},<<>>,<<>>,<<>>,<<>>,<<"erlang">>,<<>>,<<>>,<<>>,<<>>,<<>>,<<>>]]) -> 
{{error,{case_clause,nomatch}},
[{imem_statement,update_cursor_prepare,4,[{file,"imem/src/imem_statement.erl"},{line,169}]},
{imem_server,mfa,2,[{file,"imem/src/imem_server.erl"},{line,182}]},
{erlimem_cmds,exec_catch,4,[{file,"erlimem/src/erlimem_cmds.erl"},{line,35}]},
{erlimem_session,handle_call,3,[{file,"erlimem/src/erlimem_session.erl"},{line,240}]},
{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},
{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```
Current Implementation : https://github.com/K2InformaticsGmbH/imem/compare/master...dbg_tracer

Relevant parts:
### Implementation details
```erlang
% imem_tracer.hrl
-define(KEY_DEF, <<"fun(_,_R) -> imem_meta:record_hash(_R,[3,6,7,8]) end.">>).
-record(ddTrace, {
    trace_key   = ?KEY_DEF  :: binary(),
    event_type  = register  :: atom(),
    enable      = false     :: boolean(),
    process                 :: term(),
    mod         = '_'       :: atom(),
    func        = '_'       :: atom(),
    args        = '_'       :: term(),
    match_spec  = "default" :: list(),
    rate        = 0         :: integer(),
    extra                   :: term(),
    overflow    = false     :: boolean()
}).
-define(ddTrace, [
    binstr,     % trace_key
    atom,       % event_type
    boolean,    % enable
    term,       % process
    atom,       % mod
    atom,       % func
    term,       % args
    list,       % match_spec
    integer,    % rate
    term,       % extra
    boolean     % overflow
]).

% imem_meta.erl
-define(DD_TRACE_OPTS,      [{trigger,<<"fun imem_tracer:trigger/5.">>}]).
...
init_create_check_table(ddTrace, {record_info(fields, ddTrace),
                              ?ddTrace, #ddTrace{}}, ?DD_TRACE_OPTS, system),
```

**Comment by c-bik** [comment]
From: Stefan Ochsenbein (@stoch)
Sent: Freitag, 30. März 2018 12:54
To: 'Bikram Chatterjee'
Cc: Ochsenbein Stefan
Subject: AW: Need help with IMEM debugging for ddTrace

Hi Bikram

First general thoughts:

1)	Please consider hooking in the trace functionality into imem_if_mnesia instead of imem_meta.
There will be no occasion to ever use ddTrace outside of the local erlang/mnesia combination.
There is a drawback, though: imem_if_mnesia is started first and it cannot create tables.
That still has to be done in imem_meta.

2)	table_size(ddTrace) -> 0;
This seems unnecessary or misleading since the table physically may contain rows. 
There is no reason to lie about these rows

3)	-define(META_TABLES, [?CACHE_TABLE, ?LOG_TABLE, ?MONITOR_TABLE, ?CONFIG_TABLE, dual, ddNode, ddSnap, ddTrace, ddSchema, ddSize, ddAlias, ddTable]).
I wonder if we really should declare ddTrace as virtual. If at all, then it can also be done in imem_if_mnesia.
For write, read, select etc it is a physical table. The difference tweak only exists for tail, which should be implemented down in imem_if_mnesia.

Your Issue with the insert : 

I did simple tests with DDerl (simple table definition -> full featured table)

create table ddTrace(
  trace_key binstr,
  event_type atom,
  enable boolean,
  process term,
  mod atom,
  func atom,
  args term,
  match_spec list,
  rate integer,
  extra term,
  overflow boolean
)

 
![image](https://user-images.githubusercontent.com/913008/38137176-74e424b4-3423-11e8-89a5-f8fc12e58ec0.png)


The new parser cannot handle the default definition with funs any more. We have to write the default as a string and fix it in ddTable:

CREATE TABLE
    ddTrace (
        trace_key binstr default ‘fun(_,_R) -> imem_meta:record_hash(_R,[3,6,7,8]) end.’,
        event_type atom,
        enable boolean,
        process term,
        mod atom,
        func atom,
        args term,
        match_spec list,
        rate integer,
        extra term,
        overflow boolean
    )

This still works. While patching ddColumns in ddTable to the following, editing the table works as expected:

[{ddColumn
,trace_key
,binstr
,undefined
,undefined
,<<"fun(_,_R) -> imem_meta:record_hash(_R,[3,6,7,8]) end.">>
,[]
}
,{ddColumn
,event_type
,atom
,undefined
,undefined
,register
,[]
}
,{ddColumn
,enable
,boolean
,undefined
,undefined
,false
,[]
}
,{ddColumn
,process
,term
,undefined
,undefined
,undefined
,[]
}
,{ddColumn,mod,atom,undefined,undefined,'_',[]}
,{ddColumn,func,atom,undefined,undefined,'_',[]}
,{ddColumn,args,term,undefined,undefined,0,[]}
,{ddColumn
,match_spec
,list
,undefined
,undefined
,"default"
,[]
}
,{ddColumn,rate,integer,undefined,undefined,0,[]}
,{ddColumn
,extra
,term
,undefined
,undefined
,undefined
,[]
}
,{ddColumn
,overflow
,boolean
,undefined
,undefined
,false
,[]
}
]

Putting only mod=erlang gives:
![image](https://user-images.githubusercontent.com/913008/38137167-6480ec42-3423-11e8-8796-93e0910f4b29.png)


Probably, you also want to default process to ‘_’, meaning that there is no restriction or filter on this output.

Please check that you have the same in ddTable. If so, editing is somehow hindered by declaring the table as virtual. Try without as proposed above.

Let me know if this does not help. I will then download your (latest) code for debugging.

**Comment by c-bik** [comment]
@stefan thanks for your response.

Following your guideline above I did:
* removed all `ddTrace` related function override from `imem_meta` to be implemented later at `imem_if_mnesia` level.
* SQL support (CREATE etc) **isn't a concern** here, as the table is create in `imem_meta:init(...)` as follows:
![image](https://user-images.githubusercontent.com/913008/38137528-6b43cd18-3425-11e8-9818-784c713f8639.png)
![image](https://user-images.githubusercontent.com/913008/38137552-946abeea-3425-11e8-83aa-fa3ca3354030.png)

### `ddTracer` entry from `ddTable`
```json
[
    {
        "qname": "{dderl,ddTrace}",
        "columns": "[{ddColumn,trace_key,binstr,undefined,undefined,<<\"fun(_,_R) -> imem_meta:record_hash(_R,[3,6,7,8]) end.\">>,[]},{ddColumn,event_type,atom,undefined,undefined,register,[]},{ddColumn,enable,boolean,undefined,undefined,false,[]},{ddColumn,process,term,undefined,undefined,undefined,[]},{ddColumn,mod,atom,undefined,undefined,'_',[]},{ddColumn,func,atom,undefined,undefined,'_',[]},{ddColumn,args,term,undefined,undefined,'_',[]},{ddColumn,match_spec,list,undefined,undefined,\"default\",[]},{ddColumn,rate,integer,undefined,undefined,0,[]},{ddColumn,extra,term,undefined,undefined,undefined,[]},{ddColumn,overflow,boolean,undefined,undefined,false,[]}]",
        "opts": "[{trigger,<<\"fun imem_tracer:trigger/5.\">>}]",
        "owner": "system",
        "readonly": "false"
    }
]
```

### `columns` of `ddTracer` table
```erlang
[
    {ddColumn,trace_key,binstr,undefined,undefined,<<"fun(_,_R) -> imem_meta:record_hash(_R,[3,6,7,8]) end.">>,[]}
    ,{ddColumn,event_type,atom,undefined,undefined,register,[]}
    ,{ddColumn,enable,boolean,undefined,undefined,false,[]}
    ,{ddColumn,process,term,undefined,undefined,undefined,[]}
    ,{ddColumn,mod,atom,undefined,undefined,'_',[]}
    ,{ddColumn,func,atom,undefined,undefined,'_',[]}
    ,{ddColumn,args,term,undefined,undefined,'_',[]}
    ,{ddColumn,match_spec,list,undefined,undefined,"default",[]}
    ,{ddColumn,rate,integer,undefined,undefined,0,[]}
    ,{ddColumn,extra,term,undefined,undefined,undefined,[]}
    ,{ddColumn,overflow,boolean,undefined,undefined,false,[]}
]
```

**The crach is however still the same!**

**Comment by stoch** [comment]
Did you try by removing the trigger?

**Comment by stoch** [comment]
@c-bik you are disallowing all operations except truncate in the trigger:

![image](https://user-images.githubusercontent.com/1941407/38138064-ecaefe7e-3428-11e8-93cf-74939c876393.png)

**Comment by c-bik** [comment]
@stoch no haven’t tried without the trigger! But I was hoping to see that exception. I will try without the trigger and post update here!

**Comment by stoch** [comment]
@c-bik Triggers must be declared as fun texts, not in the compact form 
fun some_module/arity end.
This is to allow for indexing extensions by manipulating the trigger body.

**Comment by c-bik** [comment]
@stoch Thanks a lot 👍 👍 

> triggers must be declared as fun texts, not in the compact form fun some_module/arity end.

that was it, going forward with implemetation at `imem_if_mnesia level`.
