### ISSUE TITLE
Incomplete cluster snapshot on test 1

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/imem#218]
The following tables are registered for cluster snapshot:
```erlang
[{imem,imem_snap,snapshotClusterTables}]	[ddAccount,ddAlias,ddRole,ddCmd,ddConfig,ddConn,ddDash,ddView,ddInterface,mtrac,sac,stat,subs,toac,tpac,cbx]
```
The zip file 
`D:\K2Informatics\sbsgui\snapshot\backup_snapshot_20180920_081722.971120.zip`
only contains these files:

![image](https://user-images.githubusercontent.com/1941407/45799675-97170600-bcae-11e8-946a-f8166c176750.png)

Empty tables will not be included. That is debatable but maybe ok.
The following non-empty tables are missing in the zip:
- ddInterface 
- cbx

**Comment by shamis** [comment]
It seems like the tables `ddInterface` and `cbx` are getting backed up in the backup_snapshot zip file
![image](https://user-images.githubusercontent.com/3499591/47030622-53f56900-d16e-11e8-96f9-96862a66c254.png)

If the config (snapshotClusterTables) is changed it will be only effective once the snapshot is done.
