### ISSUE TITLE
procss_statistics metric

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/imem#227]
cc @acautin and @shamis 

**Meritc**: `procss_statistics`
**Description**: Maximum and/or minimum values of some (numeric) `erlang:process_info/1` properties of all registered process (retruned in `erlang:registered/0`) as map

Erlang currently returns the following numeric propertices from `erlang:process_info(pid())`

Process Info|Definition
---|---
`heap_size` | The size in words of the youngest heap generation of the process. This generation includes the process stack
`message_queue_len` | The number of messages currently in the message queue of the process
`reductions` | Number of reductions executed by the process
`stack_size` | The stack size, in words, of the process
`total_heap_size` | The total size, in words, of all heap fragments of the process. This includes the process stack and any unreceived messages that are considered to be part of the heap

The following matrices are calculated from it:

Metric|Definition
---|---
`max_heap_size` | Max `heap_size` among currently registered processes
`max_message_queue_len` | Max `message_queue_len` among currently registered processes
~`reductions`~ | This is a monotonically increasing value for each process which doesn't convey any useful information without the process identity
`max_stack_size` | Max `stack_size` among currently registered processes
`max_total_heap_size` | Max `total_heap_size` among currently registered processes

**Overload Protection**: The values are cached for a configurable period of time before re-calculation

### Notes
* To be implemented solely in `imem_metrics` module
* Only [`erlang:registered/1`](http://erlang.org/doc/man/erlang.html#registered-0) (locally regsireted) process are considered. **Processes registered globally [`global:registered_names/0`](http://erlang.org/doc/man/global.html#registered_names-0) are not considered**

**Comment by acautin** [comment]
@c-bik based on @stoch feedback please include the name of the registered processes with the max value.

**Comment by shamis** [comment]
so the suggested format for metric response is (including the name of the process with max value)
```erlang
#{max_heap_size => #{process => process_regter_name_atom(), value => number()},
  max_message_queue_len => #{process => process_regter_name_atom(), value => number()},
  max_stack_size => #{process => process_regter_name_atom(), value => number()},
  max_total_heap_size => #{process => process_regter_name_atom(), value => number()}
}
```
cc @acautin
