### ISSUE TITLE
`to_ipaddr` not supported in SQL expressions

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/imem#230]
```sql
select * from dual where X = to_ipaddr('1.2.3.4')
```

**Comment by stoch** [comment]
Better query (tested on ZHH management):

```
select
    to_ipaddr('1.2.3.4')
from
    dual
```

![image](https://user-images.githubusercontent.com/1941407/53865787-4a22b400-3ff0-11e9-9431-91d14cc16b3d.png)
