### ISSUE TITLE
reserved column check not working with latest sqlparse.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/imem#242]
In latest sqlparse(4.6.0) function ``sqlparse:is_reserved_column`` used here:

https://github.com/K2InformaticsGmbH/imem/blob/master/src/imem_meta.erl#L1716

was removed, so imem is now incompatible with latest sqlparse.

**Comment by stoch** [comment]
@acautin This is a known fact. sqlparse 4.6.0 cannot be deployed yet. The fix in imem_meta is trivial, though. sqlparse:is_reserved() must also be called for detecting column clashes (instead of sqlparse:is_reserved_column)

**Comment by acautin** [comment]
@stoch thanks for the reply, it wasn't a known fact by me so created the issue in case someone else using master on local dev doesn't spend time debugging it.

**Comment by walter-weinmann** [comment]
4.6.0 is now in production.
