### ISSUE TITLE
ddVersion links missing in OS X top level application. 

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/imem#251]
ddVersion doesn't generate git url links for top level applications in OS X development environment.

**Comment by acautin** [comment]
For context erlang files contains a local path instead:
![Screenshot 2019-08-22 at 13 53 18](https://user-images.githubusercontent.com/949102/63512491-40303700-c4e4-11e9-9618-e8f5f6519679.png)

**Comment by shamis** [comment]
fixed with https://github.com/K2InformaticsGmbH/imem/issues/291
