### ISSUE TITLE
009052 imem clock API using QueryPerformanceFrequency NIF

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/imem#264]
Ref: https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancefrequency

**Comment by stoch** [comment]
@c-bik Please consider providing two additional API functions to directly get clock_counters for calibrated ms and usec clocks by doing the calibration internally. For a quick win, to be first implemented in Erlang and maybe later in C if the overhead can be reduced significantly. Consider a call frequency of 10'000/sec in the router app when deciding to go through the hassle of doing long integer math in C.
