### ISSUE TITLE
session id should be hashed

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/imem#35]
In imem, it is only nexessary to distinguish different session id from each other. A phash2 instead of the full session cookie is sufficient.
For rare testing cases, it might be useful to switch back to have the full session cookie but normally, this presents a security risk. Keeping the session cookie in ETS might be ok but if it can be be avoided, it should.

**Comment by c-bik** [comment]
@stoch https://github.com/K2InformaticsGmbH/dderl/issues/111 is fixed and closed.
Since caller application is free to choose SessionID and IMEM poses no restriction to it, this is not a IMEM issue.
Individual issues to be created for other application.
Closing as can't be fixed/addressed in IMEM.
