### ISSUE TITLE
RESTful SKVH interface

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/imem#37]
**API Design goals are**
- Standard behavior for simple CRUD operations in the absence of behavior modifiers
- Some study is needed on how a “standard” REST API normally should work (see references)
- Behavior modifiers for typical skvh semantics (existing skvh-API must be mappable)
- Mechanism needed to implement all existing variations, e.g. {key,hash} tuples for quick sync checks 

**URI-based proposal**
- “channel” as part of the URI instead of using “table” in a request object (the channel name could be a join or a transformation function or a behavior name)
- GET in default form (URI ending with key) should probably return a plain value JSON object for key
#### GET
- URL Prefix `https://domain.com/vX/` (vX denotes API version, X = 0,1,2,3...)

| Comment__________ | URL | Example |
| --- | --- | --- |
| list all objects as JSON array | _channel_ | `sourcePeers` |
| list attribute projection for all objects | _channel_?jp=_json_path_ | `sourcePeers?jp={NAME,CHANNEL}` |
| get single object as JSON | _channel_ / _key_ | `sourcePeers/[“smpp”,1234]` |
| list next bigger key, return single element array or [] | _channel_?jp=_json_path_&keyGT=_key1_&limit=1 | `sourcePeers?jp=#key&keyGE=[“smpp”,1234]&limit=1` |
| list object with next bigger key, return one element array or [] | _channel_?keyGT=_key1_&limit=1 | `sourcePeers?keyGT=[“smpp”,1234]&limit=1` |
| pagination / range scan of objects from startkey to endkey and/or from startkey till object count limit, return JSON array | _channel_?jp=_json_path_&keyGT=_key1_&keyLT=_key2_&limit=X | `sourcePeers?jp=#key&keyGE=[“smpp”,1234]&limit=10` |

**References**
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api
http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by stoch** [comment]
By using jp=.... in above definition we avoid ambiguities between the string representation of a key and a json path expression. Both could be [1,2,3] for example.
This means that the client has to know where the (relational) table ends and its document begins.

It is questionable if a json_path should begin with a ":" to denote the first decent into a sub-object. It probably could be skipped.
jp=WHITELIST[1,2] would represent the array of (the first two at max) whitelist entries of the selected object. WHITELIST must be an array attribute of the selected object in this case.
jp=ACCESS:WHITELIST would represent the whitelist (whole list) if WHITELIST is an attribute in the sub-object ACCESS of the selected object.

**Comment by c-bik** [comment]
@shamis As a low priority
Can you please cross check with the mail conversation (between me and @stoch sub : *Securing REST interfaces* on 16.08.2015) if there are any missing/wrong information in this issue's description above?

**Comment by shamis** [comment]
Feature migrated to [DDErl](https://github.com/K2InformaticsGmbH/dderl/commit/be3298f7f3cd22baaa1a95c3dc0077ad7b96c11d) and released with [DDErl-1.6.8](https://github.com/K2InformaticsGmbH/dderl/blob/1.6.8/src/dderl_rest.erl)
