### ISSUE TITLE
eunit fails in 18.0

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/imem#47]
Error details in Travis:
Total 4.
https://travis-ci.org/K2InformaticsGmbH/imem#L4345-L4366
https://travis-ci.org/K2InformaticsGmbH/imem#L4381-L4401
https://travis-ci.org/K2InformaticsGmbH/imem#L4720-L4756 (2 fails)

**Comment by stoch** [comment]
restructured the tests
travis does not complain any more.
