### ISSUE TITLE
Slowdown of restore throughput with number of records

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/imem#66]
The import throughput of tables drops with large snapshot file sizes (megabytes).
Example: Rows read after x seconds for restore of current toac.bkp (125'000 rows):

![2016-01-29 10_51_34-microsoft excel - mappe1](https://cloud.githubusercontent.com/assets/1941407/12672470/cf6ee97c-c676-11e5-886c-4576c9bb29e3.png)

A solution will be required for imports with more than 500'000 rows.

**Comment by c-bik** [comment]
Total time to restore is now in linear function of number of rows.

@stoch Please re-evaluate the graph

Had to sacrifice reporting details (actual rows inserted / deleted / added etc). Now it only reports number of inserted / updated / erased.
