### ISSUE TITLE
Cluster snapshot does not work on sbsgui staging

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/imem#69]
Seen on zhh02 staging with the following configuration:

[{imem,imem_snap,snapshotCluster}]	true
[{imem,imem_snap,snapshotClusterHourOfDay}]	14
[{imem,imem_snap,snapshotClusterHourOfDay},'sbsgui@oltapmos-sbsh02.it.bwns.ch']	10
[{imem,imem_snap,snapshotClusterHourOfDay},'sbsgui@oltapmos-sbsh03.it.bwns.ch']	14
[{imem,imem_snap,snapshotClusterHourOfDay},'sbsgui@zhhapmos-sbsh02.it.bwns.ch']	18
[{imem,imem_snap,snapshotClusterHourOfDay},'sbsgui@zhhapmos-sbsh03.it.bwns.ch']	22

**Comment by c-bik** [comment]
@stoch Verified in ZHH mgmt
